#cloud-config
# Add groups to the system
# Adds the ubuntu group with members 'root' and 'sys'
# and the empty group hashicorp.
groups:
  - ubuntu: [root,sys]

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: terraform
    gecos: terraform
    shell: /bin/bash
    primary_group: terraform
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDSGnwdM9w3rgAhzwFynS9gy+ouJuAQEJdrlQpeu2s3FVWyqDHh34cYvp9XIKVVkGkA+PJ1m8bMNdhfL11Jg6UJ7Z3FV0lBK+i+9IzGxlb0O4NgpVzwxmPYeRfd/I3I2geVna//MWepKvoHxajorMr3uD+BG7uJ9k426PKeSc5Wqa8MTz1P1k8UeSbHhcAMr0AzKbxWLU8kal/PCpZhV5qezeilC2BCvu7sRrr54zB3CCNZTbizT9UcFvgRiKl/a3+owH840qbTGRzCaEZnNmOCITuHA94y6h5DtOa7aAt2pPT2SItswPuFWtN2O4yycHx7EqbRdR2hhCXgGnRF0EHjT6T09LH9azxpPRxJ+D3SzHFzuPp1rgnjCCouBDY2hEKhTG7FYn8rYo5rQmdqdE8F/n5RpPAXE4FVYElD6hK/KSpDDCld9kVRqL8S0HbaPaY+fJnxLYkEmbTTky4Z8PZbrjwee3NmPUN0CJ79fB6L+qSWAwTBVwXjQcQ9sgTJ89KPqAjAKhMOzFLgEhfRTn/uDKZdxc8ky75E69qHcMctRoRUTEwGeRwPI2hOkZDtU1n9w+XDsJCNZaosGXVmph9R+cQTWMhgJPiXKfyPbuAbN0EH93caySpFsb3fTUJo33VPg9xmcMBKaE5mvzh8hzWPDFU4GNh68An4Okftgh1NMQ== Lab Computer
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC6mBPpDjHU0HRMaCcwaT9A0uRwMQwL8/mw006GORbHxMLlLPuBb3Ogd2jtQ9HDeKqCtKh+GPcNxulnXKj6MmbUyF697V7DQxed3+GgclYxnCp1lpoGjEgUiLMj4gX/MQMfjdQx0uqGFcktxyT+Jbcce2Un6U5CThmgDl1MhqZ75JOuVUtzJDxan08GKRn2DwlYNY8VJrvKIPry4cnul7G48/hT0mCcJpQbber8ZOkK9mviDqD6kj0uRHCVUF29KHH3z1ZV+sD7z3wTlGBHocAlagNjlGGoZBh6TJyAClDJIuEllkOd+F41Q4j8XiTRriv6Lo+7hf/y89izAIRMORYVIKHBynH2XkxFe8vZf2k8FU23Jo5dozAF+cVDNmM1wlURzCepw3aEyvmM0I9XcQpABDKLvR2pQtejyKiPMtxpXwnzQFXSpv/K/lDca2Ns47fDeVBzSbFQl9vHOufqvTEW5qNUSSvLTCw/iH+1SIX3sZsJh6hNJSjjrITxyJsjjD/nhdJOT9oAXtwfc0aS2MsCjt02O2DIKQG2tcLlcikCcW8xzmY/SyW4J0vr7Bc6nPOINpHpAW7OzfeMvlLqo5HfvYv1Q0s0f4SDnPs/nvyD9sGMCjnJmGLyilM2m9ajBu/4C1//q4RE2gUDXKXTkPesIgNPjW5CWubrEwjiKlBNtQ== pi@raspberrypi
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDOjIxU0cWwJmjitLA0lMqX0KOeGCHIe/rE8bV3yupXi38Kdy2ImBaedXc9wbXTMtBwtTe8uJioL2CRF7zzPHfD7mQK7gJmKaxwol2XAlnzdQD5rhEkpHNZQqCknJm8064Itq1SkoyB8mv3PFo/H80tpCpSZm8teM92EfH3G15DwDjaV8vV38OkcOOeqD3Spc5Pz7okIaonMScY/0PQCq3yoBelM1uvfB4fANxYLn9BpVv1j9wfeCdnOzmdOL4Cnc9MIyAYbnPcOQPn7nk9eAXS3q6CfqQ7894FQjN82J8j0Yy62GkChGRE5qGzvDiQhqvifS+91vS+aZbPwLmXRhfJoEZSkrjzd75XiDAGsMGMcjRBZ1bJARDxbP3WYwBX5PkQOFMqUdV8/x3pONTPjAgi+ktpJzEuASrTbDeqPZtNmXBremHVvbjXnzXb0bYYHwI8p96CA0EOtq/6N5uNHT0Q0xSAWGpdqHXYXtjDwihSg2JVu3rG32//CxtBYhduFFaVVgV4Lwz6piUn7fVKM6Z4TfBRCEXH8YUidjiBjJytEDisCqSRV4n6TD1tjHYS9GImrT3qdjlQN5uJyRUZWnudFxKlsE5fGPjcofZyWRAj6mNk/UY6xtJ4D5CCnW1HwLc99WWnyuSYV1Co0ZzkCzfhxu9R+TtMSvg9tYy+gkb0gw== pi@raspberrypi
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCxLoX5bEhThzp9i3H3QSwlTROKu2Hua6w8DIiUDsflnSEaqT96jHr1eYIzkmiL8S+COaKZG4IqTKTmAh71EGLq9iPLFM7lxiRdjG9zLf9ppewyqquYdtVtonSHhlvFccL1RJ2IhNjFfuOx6MUg0YXsIIMNI2GJkAio6PUT6e6xWoGiF1VxOI3ySPiD8Fpbnl0d3LX5sSGCuQ7xlTMJ+4s7rd41Cyo63y8S/S7ASOXI8qSj4fIs7FCvtUeWIA8F/XWg2d6XZo9GgofzPsN1fuZyQOREkIz/4J2DVBtkBqFYoEwUuDBYvTI8rx00+6A4cTj9Y5Bzw73Z5LdS1OTHxlSA5GNS1yHj5yLXncR8sMzw50WjxWNHT8i9Djzaq5FsMZpnfUTUQC2NNhj388xL8bIax2z/Bnx6gKieRYvd40mnPZpwlfyt77lezLSsc4i7oVSKnLYNsWtjbeaaGkMvvKtLDkPVFOjrR7brFmYn1tli6MxHVPzoHOJCMajfPSinSOy53py/nQYs02Mb7UsIPtxYd+tSjXwdiIFkHZLHpaR66BZwYeeq1GWZ44dUlpWl1q8YIDXLsN2elEG9Z84XTsm+rR/ULAIkLXfdk+wS1bKglulEXDGFHvfMK7zok7L8R5+m/GKqRNDyP8Dul0Lujcp+MF2Nsw6LrTyGdbYAfmHxWQ== salmonjetson@salmonjetson

# Downloads the iperf3 package
packages:
  - wget

# Runs iperf3
runcmd:
  - sudo su terraform
  - |
    sudo tee '/etc/apt/apt.conf.d/01ubuntu' <<'EOF'
    APT
    {
      Default-Release "focal";
    };
    EOF
  - sudo echo 'deb http://ftp.ca.debian.org/debian buster main' >> /etc/apt/sources.list
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 648ACFD622F3D138 0E98404D386FA1D9 DCC9EFBF77E11517
  - sudo apt update
  - sudo apt install -y libiperf0=3.6-2 iperf3=3.6-2
  - sudo apt-mark hold iperf3
  - iperf3 -s -J -D --forceflush --logfile /home/terraform/${region}-throughput-server-send.$(date -u +"%Y-%m-%d_%H-%M-%S").log
  - iperf3 -s -J -D --forceflush --logfile /home/terraform/${region}-throughput-server-receive.$(date -u +"%Y-%m-%d_%H-%M-%S").log -p 5202
